<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$sl_templates         = new Puck_Press_Stat_Leaders_Template_Manager();
$sl_templates_meta    = $sl_templates->get_registered_templates_metadata();
$selected_sl_template = $sl_templates->get_current_template_key();
$sl_more_link         = get_option( 'pp_stat_leaders_more_link', '' );
$sl_show_team         = (bool) get_option( 'pp_stat_leaders_show_team', 1 );
?>

<!-- Stat Leaders Color Palette Modal -->
<div id="pp-stat-leaders-paletteModal" class="pp-modal-overlay-palette">
	<div class="pp-modal-palette">
		<button class="pp-modal-close" id="pp-stat-leaders-palette-modal-close">✕</button>
		<div class="pp-form-row">
			<div class="pp-modal-header">
				<h3 class="pp-modal-title">Customize Stat Leaders</h3>
				<p class="pp-modal-subtitle">Style the stat leaders widgets.</p>
			</div>

			<div class="pp-modal-header">
				<label for="pp-stat-leaders-template-selector">Choose a Template:</label>
				<select id="pp-stat-leaders-template-selector">
					<?php foreach ( $sl_templates_meta as $key => $template ) : ?>
						<option value="<?php echo esc_attr( $key ); ?>" <?php selected( $key, $selected_sl_template ); ?>>
							<?php echo esc_html( $template['name'] ); ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>

		<div class="pp-modal-content">
			<form id="pp-stat-leaders-color-palette-form">
				<p class="pp-section-label">Colors</p>
				<div class="pp-form-row" id="pp-stat-leaders-dynamic-color-fields">
					<!-- Color inputs generated by JS -->
				</div>

				<p class="pp-section-label pp-section-label--typography">Typography</p>
				<div class="pp-form-row" id="pp-stat-leaders-dynamic-font-fields">
					<!-- Font inputs generated by JS -->
				</div>

				<p class="pp-section-label" style="margin-top:16px;">Team Colors</p>
				<p style="font-size:0.8rem;color:#5f6368;margin:0 0 10px;">Assign a background color to each team's leader card.</p>
				<div class="pp-form-row" id="pp-stat-leaders-team-color-fields">
					<!-- Team color inputs generated by JS -->
				</div>

				<p class="pp-section-label" style="margin-top:16px;">Widget Settings</p>
				<div class="pp-form-row" style="flex-direction:column;gap:10px;">
					<label style="display:flex;align-items:center;gap:8px;font-size:0.875rem;">
						<input type="checkbox" id="pp-stat-leaders-show-team" <?php checked( $sl_show_team ); ?>>
						Show team name on player cards
					</label>
					<label style="display:flex;flex-direction:column;gap:4px;font-size:0.875rem;">
						<span>"More" link URL <span style="color:#5f6368;font-size:0.8rem;">(leave empty to hide the link)</span></span>
						<input
							type="text"
							id="pp-stat-leaders-more-link"
							value="<?php echo esc_attr( $sl_more_link ); ?>"
							placeholder="/stats"
							style="padding:6px 10px;border:1px solid #ddd;border-radius:4px;font-size:0.875rem;">
					</label>
				</div>
			</form>
		</div>

		<div class="pp-modal-footer">
			<button class="pp-button pp-button-secondary" id="pp-cancel-save-stat-leaders-colors">Cancel</button>
			<button class="pp-button pp-button-primary" id="pp-stat-leaders-palette-save-colors">Save Colors</button>
		</div>
	</div>
</div>
