<?php

if (!defined('ABSPATH')) {
    exit;
}

$stats_templates      = new Puck_Press_Stats_Template_Manager();
$stats_templates_meta = $stats_templates->get_registered_templates_metadata();
$selected_stats_template = $stats_templates->get_current_template_key();
?>

<!-- Stats Color Palette Modal -->
<div id="pp-stats-paletteModal" class="pp-modal-overlay-palette">
    <div class="pp-modal-palette">
        <button class="pp-modal-close" id="pp-stats-palette-modal-close">✕</button>
        <div class="pp-form-row">
            <div class="pp-modal-header">
                <h3 class="pp-modal-title">Customize Colors</h3>
                <p class="pp-modal-subtitle">Style your stats leaderboard table.</p>
            </div>

            <div class="pp-modal-header">
                <label for="pp-stats-template-selector">Choose a Template:</label>
                <select id="pp-stats-template-selector">
                    <?php foreach ($stats_templates_meta as $key => $template) : ?>
                        <option value="<?php echo esc_attr($key); ?>" <?php selected($key, $selected_stats_template); ?>>
                            <?php echo esc_html($template['name']); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="pp-modal-content">
            <form id="pp-stats-color-palette-form">
                <p class="pp-section-label">Colors</p>
                <div class="pp-form-row" id="pp-stats-dynamic-color-fields">
                    <!-- Color inputs generated by JS -->
                </div>
                <p class="pp-section-label pp-section-label--typography">Typography</p>
                <div class="pp-form-row" id="pp-stats-dynamic-font-fields">
                    <!-- Font inputs generated by JS -->
                </div>
            </form>
        </div>

        <div class="pp-modal-footer">
            <button class="pp-button pp-button-secondary" id="pp-cancel-save-stats-colors">Cancel</button>
            <button class="pp-button pp-button-primary" id="pp-stats-palette-save-colors">Save Colors</button>
        </div>
    </div>
</div>
