<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$schedule_id              = isset( $_GET['schedule_id'] ) ? (int) $_GET['schedule_id'] : 1;
$record_templates         = new Puck_Press_Record_Template_Manager( $schedule_id );
$record_templates_meta    = $record_templates->get_registered_templates_metadata();
$selected_record_template = $record_templates->get_current_template_key();
?>

<!-- Record Card Color Palette Modal -->
<div id="pp-record-paletteModal" class="pp-modal-overlay-palette">
	<div class="pp-modal-palette">
		<button class="pp-modal-close" id="pp-record-palette-modal-close">✕</button>
		<div class="pp-form-row">
			<div class="pp-modal-header">
				<h3 class="pp-modal-title">Customize Colors</h3>
				<p class="pp-modal-subtitle">Style your team record card.</p>
			</div>

			<div class="pp-modal-header">
				<label for="pp-record-template-selector">Choose a Template:</label>
				<select id="pp-record-template-selector">
					<?php foreach ( $record_templates_meta as $key => $template ) : ?>
						<option value="<?php echo esc_attr( $key ); ?>" <?php selected( $key, $selected_record_template ); ?>>
							<?php echo esc_html( $template['name'] ); ?>
						</option>
					<?php endforeach; ?>
				</select>
			</div>
		</div>

		<div class="pp-modal-content">
			<form id="pp-record-color-palette-form">
				<p class="pp-section-label">Colors</p>
				<div class="pp-form-row" id="pp-record-dynamic-color-fields">
					<!-- Color inputs generated by JS -->
				</div>
				<p class="pp-section-label pp-section-label--typography">Typography</p>
				<div class="pp-form-row" id="pp-record-dynamic-font-fields">
					<!-- Font inputs generated by JS -->
				</div>
			</form>
		</div>

		<div class="pp-modal-footer">
			<button class="pp-button pp-button-secondary" id="pp-cancel-save-record-colors">Cancel</button>
			<button class="pp-button pp-button-primary" id="pp-record-palette-save-colors">Save Colors</button>
		</div>
	</div>
</div>
